-   id: check-cfn
    name: Check CFN
    description: This hook checks json files for parseable syntax.
    entry: check-cfn
    language: script
    types: [json]
    # for backward compatibility
    files: ''
    minimum_pre_commit_version: 0.15.0
-   id: check-cfn-no-export
    name: Check CFN No Export
    description: This hook checks that the CFN template does not have any exported outputs.
    entry: check-cfn-no-export
    language: script
    types: [json]
    # for backward compatibility
    files: ''
    minimum_pre_commit_version: 0.15.0
